"""Thin syslib Conan recipe generated by scripts/generate_syslib_recipes.py."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

from conan import ConanFile
from conan.tools.files import copy

def _load_helper() -> object:
    recipe_dir = Path(__file__).resolve().parent
    for candidate in (recipe_dir, recipe_dir.parent):
        helper_path = candidate / "_syslib.py"
        if not helper_path.is_file():
            continue
        spec = importlib.util.spec_from_file_location("_syslib", helper_path)
        if spec is None or spec.loader is None:
            continue
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    raise ImportError("Conan recipe helper _syslib.py was not exported beside the recipe")


_syslib = _load_helper()


class SyslibRecipe(ConanFile):
    name = "zstd-linux-x64-gnu"
    description = "libzstd static library and headers for zstd-sys"
    license = "BSD-3-Clause OR GPL-2.0-only"
    package_type = "header-library"
    no_copy_source = True
    settings = "os", "arch"

    def export(self):
        copy(
            self,
            "_syslib.py",
            src=Path(__file__).resolve().parent.parent.as_posix(),
            dst=self.export_folder,
        )

    def validate(self):
        _syslib.validate(self)

    def build(self):
        _syslib.build(self)

    def package(self):
        _syslib.package(self)
