"""Thin syslib Conan recipe generated by scripts/generate_syslib_recipes.py."""

from __future__ import annotations

import sys
from pathlib import Path

from conan import ConanFile
from conan.tools.files import copy

_RECIPE_DIR = Path(__file__).resolve().parent
for _candidate in (_RECIPE_DIR, _RECIPE_DIR.parent):
    if (_candidate / "_syslib.py").is_file() and str(_candidate) not in sys.path:
        sys.path.insert(0, str(_candidate))
import _syslib  # noqa: E402


class SyslibRecipe(ConanFile):
    name = "zstd-windows-arm64"
    description = "libzstd static library and headers for zstd-sys"
    license = "BSD-3-Clause OR GPL-2.0-only"
    package_type = "header-library"
    no_copy_source = True
    settings = "os", "arch"

    def export(self):
        copy(
            self,
            "_syslib.py",
            src=Path(__file__).resolve().parent.parent.as_posix(),
            dst=self.export_folder,
        )

    def validate(self):
        _syslib.validate(self)

    def build(self):
        _syslib.build(self)

    def package(self):
        _syslib.package(self)
