#!/usr/bin/env python3
"""Generate index.html landing page for the soldr-toolchain manifest site.

Reads the v1 Index (manifest.json) from the asset tree and emits a small
static HTML page summarising the catalog: tool name, summary, channels,
direct link to each per-tool Catalog.

Output goes next to the manifest tree so a single `assets` branch serves
both raw JSON (for tooling) and rendered HTML (for humans) via GitHub Pages.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path
from typing import Any

PAGE_TEMPLATE = """\
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>soldr-toolchain manifest</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
            max-width: 880px; margin: 2.5rem auto; padding: 0 1rem; color: #1a1a1a; line-height: 1.55; }}
    h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; }}
    .lede {{ color: #555; margin-top: 0; margin-bottom: 2rem; }}
    code, pre {{ font-family: SF Mono, Menlo, Consolas, monospace; font-size: 0.92rem; }}
    pre {{ background: #f5f5f7; padding: 0.85rem; border-radius: 6px; overflow-x: auto; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1rem 0 2rem; }}
    th, td {{ text-align: left; padding: 0.55rem 0.7rem; border-bottom: 1px solid #eee; vertical-align: top; }}
    th {{ background: #fafafa; font-weight: 600; }}
    .chan {{ display: inline-block; background: #eef; color: #224; border-radius: 3px;
             padding: 0 0.4rem; margin-right: 0.3rem; font-size: 0.85rem; }}
    a {{ color: #0366d6; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    footer {{ color: #888; font-size: 0.85rem; margin-top: 3rem; border-top: 1px solid #eee; padding-top: 1rem; }}
  </style>
</head>
<body>
  <h1>soldr-toolchain</h1>
  <p class="lede">
    Public catalogue of third-party tool releases consumed by
    <a href="https://github.com/zackees/soldr">zackees/soldr</a>'s CI.
    Conforms to the <a href="https://github.com/zackees/manifest.json">manifest.json v1 schema</a>.
  </p>

  <h2>Top-level manifest</h2>
  <p><a href="manifest.json"><code>manifest.json</code></a> &mdash; the federated Index document.</p>

  <h2>Tools ({tool_count})</h2>
  <table>
    <thead><tr><th>Tool</th><th>Summary</th><th>Catalog</th></tr></thead>
    <tbody>
{tool_rows}
    </tbody>
  </table>

  <h2>Resolve in Python</h2>
  <pre><code>pip install git+https://github.com/zackees/manifest.json

python -c "
import json, urllib.request
from manifest_json import resolve_in_catalog
url = 'https://zackees.github.io/soldr-toolchain/zccache/manifest.json'
catalog = json.loads(urllib.request.urlopen(url).read())
asset = resolve_in_catalog(catalog, 'zccache',
    platform={{'os': 'linux', 'arch': 'x86_64', 'libc': 'musl'}},
    channel='latest-stable')
print(asset['urls'][0])
"
</code></pre>

  <h2>Resolve with the CLI</h2>
  <pre><code>manifest-resolve &lt;(curl -fsSL https://zackees.github.io/soldr-toolchain/zccache/manifest.json) \\
    --tool zccache \\
    --platform os=linux,arch=x86_64,libc=musl \\
    --channel latest-stable
</code></pre>

  <footer>
    Generated by <code>scripts/build_site.py</code>. Source:
    <a href="https://github.com/zackees/soldr-toolchain">github.com/zackees/soldr-toolchain</a>.
  </footer>
</body>
</html>
"""


def render(index: dict[str, Any]) -> str:
    rows = []
    for name in sorted((index.get("tools") or {}).keys()):
        entry = index["tools"][name]
        desc = entry.get("descriptor", {}) or {}
        summary = entry.get("summary", "") or ""
        url = desc.get("url", "")
        rows.append(
            f'      <tr>'
            f'<td><code>{html.escape(name)}</code></td>'
            f'<td>{html.escape(summary)}</td>'
            f'<td><a href="{html.escape(url)}">{html.escape(url)}</a></td>'
            f'</tr>'
        )
    return PAGE_TEMPLATE.format(
        tool_count=len(index.get("tools") or {}),
        tool_rows="\n".join(rows),
    )


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--src",    type=Path, required=True, help="v1 tree root containing manifest.json")
    p.add_argument("--output", type=Path, required=True, help="path to write index.html")
    args = p.parse_args()
    index = json.loads((args.src / "manifest.json").read_text(encoding="utf-8"))
    args.output.write_text(render(index), encoding="utf-8")
    print(f"  wrote {args.output} ({args.output.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
