#!/usr/bin/env python3
"""Generate thin syslib recipe directories for soldr#1064.

The real implementation lives in ``recipes/_syslib.py``. This script
keeps the repetitive ``recipes/<lib>-<shape>/`` wrappers and README
dispatch snippets in sync with that table.
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
from recipes import _syslib


CONANFILE = '''"""Thin syslib Conan recipe generated by scripts/generate_syslib_recipes.py."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

from conan import ConanFile
from conan.tools.files import copy

def _load_helper() -> object:
    recipe_dir = Path(__file__).resolve().parent
    for candidate in (recipe_dir, recipe_dir.parent):
        helper_path = candidate / "_syslib.py"
        if not helper_path.is_file():
            continue
        spec = importlib.util.spec_from_file_location("_syslib", helper_path)
        if spec is None or spec.loader is None:
            continue
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    raise ImportError("Conan recipe helper _syslib.py was not exported beside the recipe")


_syslib = _load_helper()


class SyslibRecipe(ConanFile):
    name = "{name}"
    description = "{description}"
    license = "{license}"
    package_type = "header-library"
    no_copy_source = True
    settings = "os", "arch"

    def export(self):
        copy(
            self,
            "_syslib.py",
            src=Path(__file__).resolve().parent.parent.as_posix(),
            dst=self.export_folder,
        )

    def validate(self):
        _syslib.validate(self)

    def build(self):
        _syslib.build(self)

    def package(self):
        _syslib.package(self)
'''


README = """# `{name}`

Forge-built Conan recipe for `{lib}` `{version}` targeting
`{target_triple}`.

The shared implementation is in `recipes/_syslib.py`; this directory is
kept as a thin wrapper so forge can dispatch and cache one package per
`(library, target)` tuple.

## Source

{source_url}

## Dispatch

```bash
gh workflow run forge-conan.yml --repo zackees/forge \\
    -f recipe_repo=zackees/soldr-toolchain \\
    -f recipe_ref=main \\
    -f recipe_path=recipes/{name} \\
    -f name={name} \\
    -f version={version} \\
{dispatch_flags}
```

Ingested catalogue path:
`{lib}/{version}/{shape}/bundle.tar.zst`
"""


def dispatch_flags(enabled: str) -> str:
    inputs = [
        "windows_x64",
        "windows_x64_gnu",
        "windows_arm64",
        "linux_x64",
        "linux_arm64",
        "linux_x64_musl",
        "linux_arm64_musl",
        "macos_x64",
        "macos_arm64",
    ]
    lines = []
    for name in inputs:
        value = "true" if name == enabled else "false"
        suffix = " \\" if name != inputs[-1] else ""
        lines.append(f"    -f {name}={value}{suffix}")
    return "\n".join(lines)


def main() -> int:
    for lib_name, lib in sorted(_syslib.LIBRARIES.items()):
        for shape_name, shape in sorted(_syslib.SHAPES.items()):
            if shape_name in lib.unsupported_shapes:
                continue
            name = f"{lib_name}-{shape_name}"
            recipe_dir = REPO / "recipes" / name
            recipe_dir.mkdir(parents=True, exist_ok=True)
            (recipe_dir / "conanfile.py").write_text(
                CONANFILE.format(
                    name=name,
                    description=lib.description.replace('"', '\\"'),
                    license=lib.license,
                ),
                encoding="utf-8",
            )
            (recipe_dir / "README.md").write_text(
                README.format(
                    name=name,
                    lib=lib_name,
                    version=lib.version,
                    target_triple=shape.target_triple,
                    source_url=lib.source_url,
                    dispatch_flags=dispatch_flags(shape.forge_input),
                    shape=shape_name,
                ),
                encoding="utf-8",
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
